### ISSUE TITLE
Unable to open the shortcut file

### ISSUE THREAD

**Issue by edenhikri** [kevinschaich/py-imessage-shortcuts#2]
Hi there,

It appears that I am unable to open the `send-imessage.shortcut` file using Finder. Everytime I try open it with Finder, nothing happens.

I am using macOS Big Sur 11.5.1

**Comment by kevinschaich** [comment]
Please read the instructions. The minimum supported version of MacOS is Monterey:

https://github.com/kevinschaich/py-imessage-shortcuts#py-imessage-shortcuts
